# Generated by Django 4.1.7 on 2023-03-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_contact_friends_remove_contact_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
