# Generated by Django 4.1.7 on 2023-03-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='context',
            new_name='content',
        ),
    ]
